### ISSUE TITLE
Parser show errors where there are none

### ISSUE THREAD

**Issue by p00f** [TravonteD/tree-sitter-fennel#1]
In [this](https://del.dog/prustiphin) fennel file, nvim-treesitter's playground shows errors in the following places
1) `}}` on line 2
2) `{:*` on line 18
3) the first `:` on line 18
4) `})` on line 20
5) `:✖)` on line 22
6) `:✖` on line 22
see this screenshot https://imgur.com/3o1Te23

**Comment by p00f** [comment]
(the highlighting is also weird in the same screenshot, do I create another issue?)

**Comment by TravonteD** [comment]
> (the highlighting is also weird in the same screenshot, do I create another issue?)

No need, after I fix the parsing errors the highlighting should be fixed as well. If there is still some wonky highlighting after the fix, then we'll split it off to a new issue

**Comment by TravonteD** [comment]
So far I've fixed the issue with the identifiers in the table, but for the unicode character being used with the symbol on line 22 I'm going to have to write an external scanner since that can't be covered with regex. I'm actually kinda surprised that that's valid in the first place lol.

**Comment by p00f** [comment]
i could wrap it in quotes

**Comment by TravonteD** [comment]
@p00f Reinstall the parser and things should be fixed

**Comment by p00f** [comment]
updating completely broke it lol
![Screenshot from 2020-09-02 07-58-25](https://user-images.githubusercontent.com/36493671/91925185-1d894e80-ecf2-11ea-8277-ac70930c6656.png)

`:TSPlaygroundToggle` opens an empty buffer

**Comment by p00f** [comment]
Opening a terminal using `:Tnew` (https://github.com/kassio/neoterm) gives
```
Error detected while processing CursorHold Autocommands for "<buffer=9>":                                                                                                     
E5108: Error executing lua Failed to load parser: uv_dlopen: /home/p00f/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/fennel.so: undefined symbol: tree_sitter_fennel_external_scanner_create
```

**Comment by TravonteD** [comment]
Ah okay I have a pr in nvim-treesitter for that https://github.com/nvim-treesitter/nvim-treesitter/pull/375. Until it gets merged in order to have the latest version you need to compile it yourself by cloning this repo and running `make`, then copying the `fennel.so` to your installation of nvim-treesitter manually.

**Comment by p00f** [comment]
Fixed, thanks
