### ISSUE TITLE
fucntion values in tables

### ISSUE THREAD

**Issue by p00f** [TravonteD/tree-sitter-fennel#10]
File : https://github.com/p00f/dotfiles/blob/main/nvim/.config/nvim/fnl/dotfiles/module/glsetup.fnl

When the value is an inline function, there is an error:
![Screenshot from 2020-10-31 12-59-35](https://user-images.githubusercontent.com/36493671/97774387-583a2680-1b7d-11eb-933e-0e739346c268.png)

When the value is a predfined function, this happens
![Screenshot from 2020-10-31 13-33-45](https://user-images.githubusercontent.com/36493671/97774439-c7b01600-1b7d-11eb-8c16-0d1ff4a503a0.png)

**Comment by TravonteD** [comment]
Hi @p00f, try it out with the pr linked to this ticket and let me know if the error persists. Thanks for reporting!

**Comment by p00f** [comment]
Hey I get this when I try to open a fennel file now
```
Error detected while processing FileType Autocommands for "*":                                                                                                                      
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:24: ABI version mismatch : expected 9, found 12
```

I'm on master of both neovim, nvim-treesitter and this plugin (except the parser is built from the PR branch)

**Comment by p00f** [comment]
`tree-sitter` version - 0.17.2 https://www.archlinux.org/packages/community/x86_64/tree-sitter/

**Comment by TravonteD** [comment]
If you check the `package-lock.json` you're using an incompatible version of the cli tool. This parser is built using `0.16.9`. Please `npm install` and generate using `npx tree-sitter generate`

**Comment by p00f** [comment]
This seems fixed now, thanks!!
