### ISSUE TITLE
Can't use `:` as delimiter

### ISSUE THREAD

**Issue by BerkeleyTrue** [TravonteD/tree-sitter-fennel#12]
I'm writing some queries and I can't seem to distinguish between methods and functions with keyword args.

```clojure
(foo :bar)
(foo:bar)
```

Is it possible to add `:` or a keyword node?

What I've tried

```scheme
((function_call
    name: ([(identifier) @variable
            (field_expression (identifier)*)])
    (field) @method))
; captures keywords as well.

((function_call
    name: ([(identifier) @variable
            (field_expression (identifier)*)])
    ":" @punctuation.delimiter
    (field) @method))
; throws errors
```

**Comment by TravonteD** [comment]
Thanks for suggesting this, I'll have time see the implications of this come the weekend.

**Comment by TravonteD** [comment]
@BerkeleyTrue I've added `:` to the list of keywords. Test with this branch `12-colon-keyword`, if things work as expected we'll get it merged in!

**Comment by otommod** [comment]
I believe this can now be closed
