### ISSUE TITLE
Update to 0.19.2

### ISSUE THREAD

**Issue by theHamsta** [TravonteD/tree-sitter-fennel#15]
We are currently preparing a switch to the next ABI version of tree-sitter. All parsers need to be regenerated. We marked some parsers that have not yet done the update to enable users to still use them. Howevery, without the regenerated C files users will need the tree-sitter CLI installed. 

nvim-treesitter/nvim-treesitter#1000

This query causes some problems with the new runtime if you want to investigate.
```scheme
(field_expression
   (identifier)
   (field) @function)
```

**Comment by TravonteD** [comment]
Upgrade is complete

**Comment by theHamsta** [comment]
Thanks!

**Comment by theHamsta** [comment]
Did you find out what the problem with
```
;; TODO: fix me
;(field_expression
   ;(identifier)
   ;(field) @function)
```
is?
