### ISSUE TITLE
Does not recognize doted names as function names

### ISSUE THREAD

**Issue by otommod** [TravonteD/tree-sitter-fennel#21]
![20210710_03h08m33s_grim](https://user-images.githubusercontent.com/2249516/125145921-2b86d780-e12c-11eb-809c-16508f7f1fea.png)

Indeed the current code specifically requires the function name to be an identifier, which cannot be doted

https://github.com/TravonteD/tree-sitter-fennel/blob/bc689e2ef264e2cba499cfdcd16194e8f5fe87d2/grammar.js#L213-L214

**Comment by TravonteD** [comment]
Thanks for reporting this, I'll try to get to it on the weekend. In the meantime feel free to contribute a PR ;)

**Comment by TravonteD** [comment]
I've merged a fix for this in the latest master, re-install the parser and you should be good to go :+1:

**Comment by otommod** [comment]
This indeed fixes the problem. Thank you very much!
