### ISSUE TITLE
Parentheses inside let breaks syntax highlight

### ISSUE THREAD

**Issue by datwaft** [TravonteD/tree-sitter-fennel#26]
As you can see in the next image, when I use a expression like the one in the image, the syntax breaks.

![image](https://user-images.githubusercontent.com/37723586/129767025-65e60674-5df5-4526-ba54-d899f501ebbf.png)

If I use `[]` instead, the syntax works.

![image](https://user-images.githubusercontent.com/37723586/129767073-e5f00cb1-bcac-424a-afba-f0a9da41cfcf.png)

It even breaks without the `'` before the parentheses.

I am using the latest neovim nightly.

**Edit:** here is the code I used:
```clojure
(macro map! [buffer?]
  (fn cons [obj seq]
    [obj (unpack seq)])
  (let [expr '("lhs" "rhs" {})
        expr (if buffer? (cons 0 expr) expr)
        expr (if buffer?
               (cons 'vim.api.nvim_buf_set_keymap expr)
               (cons 'vim.api.nvim_set_keymap expr))]
    (list (unpack expr))))
(macrodebug (map! true))
```

**Comment by TravonteD** [comment]
Thank you for reporting this! I've pushed a fix with the latest commit https://github.com/TravonteD/tree-sitter-fennel/commit/96087b263b72b75552755a40f1f26c9510bc8f17
