### ISSUE TITLE
Create separate rule for `:keyword` style strings?

### ISSUE THREAD

**Issue by beardedsakimonkey** [TravonteD/tree-sitter-fennel#35]
Currently, it seems like there's no way to have different coloring for `:keyword` strings and `"quoted"` strings.  This is something supported by fennel.vim, FWIW.

Is this something that could be supported?

Thanks.

**Comment by TravonteD** [comment]
Can you provide a screenshot of this? They are separately hightlighted for me. This is done using a query.

**Comment by beardedsakimonkey** [comment]
Ah thanks for the pointer.  I read up on queries and managed to achieve this.  Thanks!
