### ISSUE TITLE
lambda

### ISSUE THREAD

**Issue by XeroOl** [TravonteD/tree-sitter-fennel#42]
the word "lambda" gets highlighted for me, but not the symbol "λ". Fennel supports both

**Comment by alexmozaidze** [comment]
Are you using Neovim? nvim-treesitter doesn't highlight `λ` as a function declaration in its queries, which is probably an oversight.

Here's how to fix this:
1. Create a file in `~/.config/nvim/after/queries/fennel/highlights.scm`
2. Put the following contents in there
```scm
;; extends

"λ" @keyword.function
```
3. Save the file and restart Neovim

**Comment by XeroOl** [comment]
Yes I was using NeoVim.
Seems like its been fixed upstream.
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/fennel/highlights.scm#L81

Apologies, in the future I will be sure to check if the issue comes from nvim-treesitter before reporting here
