### ISSUE TITLE
Testing against source files?

### ISSUE THREAD

**Issue by sogaiu** [TravonteD/tree-sitter-fennel#5]
I've also worked on a grammar for Fennel and have collected a list of repositories which I test against: [repositories-list.txt](https://github.com/TravonteD/tree-sitter-fennel/files/5212001/repositories-list.txt)

With clones of those made locally (e.g. under ~/src/fennel-repositories) from a tree-sitter grammar repository I typically do something like:
```
$ find ~/src/fennel-repositories -type f -regex '.*\.fnl' -print0 | xargs -0 npx tree-sitter parse --quiet > 2020-09-12.txt
```
Then I examine the results, investigate issues, tweak the grammar, etc.

May be you do something like this already, but FWIW.

**Comment by TravonteD** [comment]
Interesting idea! Currently I use the testing suite that comes with tree-sitter, and for examining errors I use [playground](https://github.com/nvim-treesitter/playground) to examine the syntax tree for different files. I appreciate the list and I will go through it to see if I can find things to improve.
