### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by theHamsta** [TravonteD/tree-sitter-fennel#9]
Could you try fuzzing for `scanner.c` with the instruction in
https://github.com/ikatyang/tree-sitter-markdown/issues/14

Apparently it's easy to get stuck in a endless loop in the scanner.c

**Comment by TravonteD** [comment]
@theHamsta  are you getting segfaults with the current build? if so, under what conditions?

**Comment by theHamsta** [comment]
No, defaults. But the parser can get sticker a endless loop. Why don't you try it out yourself. The fuzzer tests random input sequences and shows you the ones that are problematic.
